# SITE CONFIGURATION
baseurl: "/yujenlin_blog" # the subpath of your site, e.g. /blog/
url: "http://peacedove.github.io/" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Yu-Jen Lin's Blog 
  avatar: avatar.png
  gravatar: # email md5 hash
  description: "Yu-Jen Lin's Blog" # used by search engines
  
  # Header and footer text
  header_text: >
     <p>What do you learn today?</p>
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>
  
  # Icons
  rss: false
  email_address: "peacedove5210@gmail.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: "peacedove"
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: 
  wordpress: 
  youtube: "peacedove5210" 
  
  # Scripts
  google_analytics: "UA-59460328-1"
  disqus_shortname: "yujenlin-blog"
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
